#
# Travis CI configuration file for PAPPL.
#

language: c

jobs:
  include:
    # Linux-specific build stuff
    - os: linux
      dist: focal
      virt: vm
      env:
        - ASAN_OPTIONS=leak_check_at_exit=false
      script: ./configure --enable-debug --enable-maintainer --enable-sanitizer && make && make test && (cd pappl; make cppcheck)
      addons:
        apt:
          packages: [avahi-daemon, cppcheck, libavahi-client-dev, libcups2-dev, libcupsimage2-dev, libgnutls28-dev, libjpeg-dev, libpng-dev, libusb-1.0-0-dev, zlib1g-dev]

    # macOS-specific build stuff
    - os: osx
      osx_image: xcode12.2
      script: ./configure --enable-debug --enable-maintainer --enable-sanitizer && make && make test



notifications:
  email:
    recipients:
      - msweet@msweet.org
