name: Build

on:
  push:
    branches: [ v1.0.x ]
  pull_request:
    branches: [ v1.0.x ]

jobs:
  build-linux:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: install prerequisites
      run: sudo apt-get install -y avahi-daemon libavahi-client-dev libcups2-dev libcupsimage2-dev libgnutls28-dev libjpeg-dev libpam-dev libpng-dev libusb-1.0-0-dev zlib1g-dev
    - name: configure
      env:
        CC: /usr/bin/gcc
      run: ./configure --enable-debug --enable-maintainer --enable-sanitizer
    - name: make
      run: make
    - name: test
      env:
        ASAN_OPTIONS: leak_check_at_exit=false
      run: make test

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: install prerequisites
      run: brew install libjpeg libpng libusb
    - name: configure
      run: ./configure --enable-debug --enable-maintainer --enable-sanitizer
    - name: make
      run: make
    - name: test
      run: make test
